version: '3.7'

services:
  scanner:
    container_name: scanner
    restart: always
    build:
      context: ..
      dockerfile: dockerfiles/scanner.Dockerfile
    volumes:
      - ../block_numbers:/scanner/block_numbers
    command: poetry run python run.py
